.\" This file is part of DeuTex.
.\" 
.\" DeuTex incorporates code derived from DEU 5.21 that was put in the
.\" public domain in 1994 by Raphaël Quinet and Brendon Wyber.
.\" 
.\" DeuTex is Copyright © 1994-1995 Olivier Montanuy,
.\"           Copyright © 1999-2005 André Majorel.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
.\" Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License along
.\" with this library; if not, write to the Free Software Foundation, Inc.,
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
.\" 
.TH DEUTEX 6 $DATE "DeuTex $VERSION"
.SH NAME
deutex, deusf \- do things with wad files
.SH SYNOPSIS
.BR "deutex \-?" | \-h | \-help | \-\-help
.br
.B  deutex \-\-version
.br
.B  deutex \-man
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-add
.I incomplete.wad out.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-af
.I flats.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-append
.I incomplete.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-as
.I sprite.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-check
.I in.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-debug
.RI [ in.gif ]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-get
.I entry
.RI [ in.wad ]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-join
.I incomplete.wad in.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-make
\fR[\fP\fIdirctivs.txt\fP\fR] \fP\fIout.wad\fP
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-merge
.I in.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-pkgfx
.RI [ in.wad " [" out.txt ]]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-pknormal
.RI [ in.wad " [" out.txt ]]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-restor\fP
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-usedidx
.RI [ in.wad ]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-usedtex
.RI [ in.wad ]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-unused
.I in.wad
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-wadir
.RI [ in.wad ]
.br
\fBdeutex\fP [\fIoptions\fP]
.B \-xtract
.I in.wad
.RI [ dirctivs.txt ]
.br

.BR "deusf \-?" | \-h | \-help | \-\-help
.br
.B  deusf \-\-version
.br
.BI "deusf " options
.br
.SH DESCRIPTION
DeuTex is a wad composer for Doom, Heretic, Hexen and Strife.
It can be used to extract the lumps of a wad and save them as individual files
or the reverse, and much more.
.PP
When extracting a lump to a file, it does not just copy the raw data, it
converts it to an appropriate format (such as PPM for graphics, Sun audio for
samples, etc.).
Conversely, when it reads files for inclusion in pwads, it does the necessary
conversions (for example, from PPM to Doom picture format).
.PP
DeuSF is a trimmed version of DeuTex that is used to merge sprites and flats
from a pwad into an iwad, which is sometimes necessary because Doom and its
breed do not handle sprites in pwads well.
.PP
See \fBdocsrc/dtexman6.txt\fP for more information on DeuTex and DeuSF.
.SS Decomposing a wad
To decompose a wad (i.e. extract its contents), use the \fB\-extract\fP (a.k.a.
\fB\-xtract\fP) command.
When decomposing a wad, DeuTex creates one file for each lump.
The files are created in one of the following subdirectories of the working
directory: \fBflats/\fP, \fBlumps/\fP, \fBmusics/\fP, \fBpatches/\fP,
\fBsounds/\fP, \fBsprites/\fP, \fBtextures/\fP.
The decomposing process also creates a very important file, \fBwadinfo.txt\fP,
which will be used later when composing.
.PP
To extract the contents of the Doom II iwad,
.nf
	\fBdeutex \-doom2 /path/to/doom2.wad \-xtract\fP
.fi
.PP
To extract the contents of a Doom II pwad named \fImywad.wad\fP,
.nf
	\fBdeutex \-doom2 /path/to/doom2.wad \-xtract mywad.wad\fP
.fi
.PP
To extract only the sprites,
.nf
	\fBdeutex \-doom2 /path/to/doom2.wad \-sprites \-xtract\fP
.fi
.PP
To extract only the sounds and save them as .voc,
.nf
	\fBdeutex \-doom2 /path/to/doom2.wad \-sounds \-voc \-xtract\fP
.fi
.SS Composing (building) a wad
Composing is the symmetrical process.
It's done with the three commands \fB\-build\fP, \fB\-create\fP and
\fB\-make\fP, that are equivalent.
Using \fBwadinfo.txt\fP and the files in flats/, lumps/, musics/, patches/,
sounds/, sprites/ and textures/, DeuTex creates a new wad.
.PP
To create a new pwad named \fImywad.wad\fP,
.nf
.RS
\fBdeutex \-doom2 /path/to/doom2.wad \-make mywad.wad\fP
.RE
.fi
.PP
To create a new iwad named \fImytc.wad\fP,
.nf
.RS
\fBdeutex \-doom2 /path/to/doom2.wad \-iwad \-make mytc.wad\fP
.RE
.fi
.SS Other operations
DeuTex has many (too many ?) other commands like \fB\-join\fP, \fB\-merge\fP,
\fB\-usedtex\fP etc.
See \fBdocsrc/dtexman6.txt\fP for a full description.
.SH OPTIONS
$OPTIONS
.SH DIAGNOSTICS
All messages are identified by a unique code.
Some messages are identical\ ; the code is useful to distinguish them.
All codes have four characters\ ; two letters and two digits.
The letters identify the part of the code where the message comes from, the
digits give the message number within that area.
In general, numbers are assigned so that messages that come from parts of the
code that are executed earlier have lower numbers.
.SH FILES
.TP
.IB dir /flats/
When extracting, flats are saved to this directory.
When composing, flats are read from this directory.
.TP
.IB dir /graphics/
When extracting, graphics are saved to this directory.
When composing, graphics are read from this directory.
.TP
.IB dir /levels/
When extracting, levels are saved to this directory.
When composing, levels are read from this directory.
.TP
.IB dir /lumps/
When extracting, lumps are saved to this directory.
When composing, lumps are read from this directory.
.TP
.IB dir /musics/
When extracting, musics are saved to this directory.
When composing, musics are read from this directory.
.TP
.IB dir /patches/
When extracting, patches are saved to this directory.
When composing, patches are read from this directory.
.TP
.IB dir /scripts/
When extracting, Strife scripts are saved to this directory.
When composing, Strife scripts are read from this directory.
.TP
.IB dir /sneaps/
When extracting, Doom alpha sneaps are saved to this directory.
When composing, Doom alpha sneaps are read from this directory.
.TP
.IB dir /sneats/
When extracting, Doom alpha sneats are saved to this directory.
When composing, Doom alpha sneats are read from this directory.
.TP
.IB dir /sounds/
When extracting, sounds are saved to this directory.
When composing, sounds are read from this directory.
.TP
.IB dir /sprites/
When extracting, sprites are saved to this directory.
When composing, sprites are read from this directory.
.TP
.IB dir /textures/texture1.txt
The \fBTEXTURE1\fP lump (all but Doom alpha 0.4 and 0.5).
.TP
.IB dir /textures/texture2.txt
The \fBTEXTURE2\fP lump (all commercial iwads except Doom 2).
.TP
.IB dir /textures/textures.txt
The \fBTEXTURES\fP lump (Doom alpha 0.4 and 0.5).
.TP
.IB dir /wadinfo.txt
The default master file.
.SH ENVIRONMENT
.TP
.B DOOMWADDIR
The directory where the iwad resides. The value of this environment variable is
overridden by \fB\-main\fP, \fB\-doom\fP and friends.
.SH BUGS
See \fBTODO\fP.
.SH LEGAL
DeuTex is copyright © 1994-1995 Olivier Montanuy, copyright © 1999-2005 André
Majorel.
.PP
Most of this program is GPL'd but some of it is available under other licenses.
This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
See LICENSE for specific information and copyright notices.
All trademarks are the property of their owners.
.SH AUTHOR
The original author of DeuTex is Olivier Montanuy
<Olivier.Montanuy=wanadoo+fr>.
From 1994 to 1996, DeuTex was maintained by Olivier Montanuy with help from Per
Allansson <c91peral=und+ida+liu+se>, James Bonfield
<jkb=mrc-molecular-biology+cambridge+ac+uk>, Sharon Bowles, Mark Mathews
<mark.mathews=channel1+com> and Chuck Rossi.
The original manual was written by Kevin McGrail <hevkev=sfo+com>.
.PP
As of version 4 (1999), the maintainer is André Majorel
<URL:http://www.teaser.fr/~amajorel/>.
.PP
Questions and bug reports should be sent to the current maintainer, \fInot\fP
to the original authors.
.SH SEE ALSO
.BR wadcat (6),
.BR wadext (6),
.BR wadext2 (6),
.BR wadflat (6),
.BR wadgc (6),
.BR wadlc (6),
.BR wadldc (6),
.BR wadpatch (6),
.BR wadsprit (6),
.BR wadtex (6),
.BR wadtxls (6),
.BR xwadtools (6)
